(ChannelArchiverService) Support multiple index files

diff --git a/ChannelArchiverService/start_server b/ChannelArchiverService/start_server
--- a/ChannelArchiverService/start_server
+++ b/ChannelArchiverService/start_server
@@ -7,21 +7,55 @@
 #            distribution.
 #
 # Abs: start_server starts the channel archiver service, which can query a
-#      Channel Archiver index file, with a given service name 
+#      Channel Archiver index files, with a given service name 
 #
 # Rem: The Channel Archiver Service is an example of an EPICS v4 RPC service.
 # 
 #
-# Usage: start_server
-#        start_server index_file
-#        start_server index_file service_name                   
+# Usage: start_server -h
+#        start_server [-S service_name] [index_1 ... index_n]                   
 # 
 # ----------------------------------------------------------------------------
 # Auth: Dave Hickin (david.hickin@diamond.ac.uk)
 # ============================================================================
 
 TOP=$(dirname $0)
+DEFAULT_SERVICE="archiveService"
+SERVICE=${DEFAULT_SERVICE}
 
-$TOP/bin/$EPICS_HOST_ARCH/ArchiverServiceRPC ${1:-$TOP/data/fredjanet/index}  ${2:-archiveService}
+Error()
+{
+    echo "Error: $@" >&2;
+    usage
+    exit 1;
+}
+
+usage()
+{
+cat << EOF
+Usage:
+     start_server [-S service_name] [index_1 ... index_n]    
+EOF
+}
+
+while getopts :hS: OPTION
+do
+    case $OPTION in
+    h) usage
+       exit
+       ;;
+
+    S) SERVICE="$OPTARG"
+       ;;
+
+    ?) Error invalid option or missing argument
+       ;;
+    esac
+done
+shift $((OPTIND-1))
+
+ 
+$TOP/bin/$EPICS_HOST_ARCH/ArchiverServiceRPC ${SERVICE} "$@"
+
 
 
